# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1920, 1080)
        self.word_choice_lst = QtWidgets.QListWidget(window)
        self.word_choice_lst.setGeometry(QtCore.QRect(1240, 20, 361, 911))
        self.word_choice_lst.setObjectName("word_choice_lst")
        self.result = QtWidgets.QLabel(window)
        self.result.setGeometry(QtCore.QRect(20, 950, 1581, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setFrameShape(QtWidgets.QFrame.Panel)
        self.result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result.setLineWidth(4)
        self.result.setMidLineWidth(10)
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.reset_btn = QtWidgets.QPushButton(window)
        self.reset_btn.setGeometry(QtCore.QRect(760, 1020, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("reset_btn")
        self.exit_btn = QtWidgets.QPushButton(window)
        self.exit_btn.setGeometry(QtCore.QRect(910, 1020, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit_btn.setFont(font)
        self.exit_btn.setObjectName("exit_btn")
        self.camera_view = QtWidgets.QLabel(window)
        self.camera_view.setGeometry(QtCore.QRect(20, 20, 1211, 911))
        self.camera_view.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_view.setText("")
        self.camera_view.setObjectName("camera_view")
        self.clear_btn = QtWidgets.QPushButton(window)
        self.clear_btn.setGeometry(QtCore.QRect(600, 1020, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Dialog"))
        self.reset_btn.setText(_translate("window", "Reset"))
        self.exit_btn.setText(_translate("window", "Exit"))
        self.clear_btn.setText(_translate("window", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QDialog()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
