# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1359, 670)
        self.cameraView = QtWidgets.QGraphicsView(parent=window)
        self.cameraView.setGeometry(QtCore.QRect(20, 10, 931, 521))
        self.cameraView.setObjectName("cameraView")
        self.listWidget = QtWidgets.QListWidget(parent=window)
        self.listWidget.setGeometry(QtCore.QRect(970, 10, 371, 521))
        self.listWidget.setObjectName("listWidget")
        self.outputLabel = QtWidgets.QLabel(parent=window)
        self.outputLabel.setGeometry(QtCore.QRect(20, 549, 1321, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.outputLabel.setLineWidth(4)
        self.outputLabel.setMidLineWidth(10)
        self.outputLabel.setText("")
        self.outputLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.resetButton = QtWidgets.QPushButton(parent=window)
        self.resetButton.setGeometry(QtCore.QRect(530, 620, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.exitButton = QtWidgets.QPushButton(parent=window)
        self.exitButton.setGeometry(QtCore.QRect(750, 620, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Dialog"))
        self.resetButton.setText(_translate("window", "Reset"))
        self.exitButton.setText(_translate("window", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QDialog()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())
